export const input = [
  {
    id: '1',
    url: 'url1',
    titulo: 'string',
    description: 'string',
    noticia: 'string',
    imagen_frontal: 'string',
    imagen_mini: 'string',
  },
  {
    id: '2',
    url: 'string',
    titulo: 'string22hhh222222',
    description: 'string',
    noticia: 'string',
    imagen_frontal: 'string',
    imagen_mini: 'string',
  },
  {
    id: '3',
    url: 'string',
    titulo: 'strinaaag22222222',
    description: 'string',
    noticia: 'string',
    imagen_frontal: 'string',
    imagen_mini: 'string',
  },
  {
    id: '4',
    url: 'stringed',
    titulo: 'strinssg22222222',
    description: 'string',
    noticia: 'string',
    imagen_frontal: 'string',
    imagen_mini: 'string',
  },
  {
    id: '5',
    url: 'stringggvd',
    titulo: 'stringtrthrt22222222',
    description: 'string',
    noticia: 'string',
    imagen_frontal: 'string',
    imagen_mini: 'string',
  },
  {
    id: '6',
    url: 'stringxcvxc',
    titulo: 'strirthgntrgg22222222',
    description: 'string',
    noticia: 'string',
    imagen_frontal: 'string',
    imagen_mini: 'string',
  },
  {
    id: '7',
    url: 'stringfvfv',
    titulo: 'stringsfsfdf22222222',
    description: 'string',
    noticia: 'string',
    imagen_frontal: 'string',
    imagen_mini: 'string',
  },
  {
    id: '8',
    url: 'stringfvvxa',
    titulo: 'sdsdfsdf',
    description: 'string',
    noticia: 'string',
    imagen_frontal: 'string',
    imagen_mini: 'string',
  },
  {
    id: '9',
    url: 'strin',
    titulo: 'string222sfsf22222',
    description: 'string',
    noticia: 'string',
    imagen_frontal: 'string',
    imagen_mini: 'string',
  },
  {
    id: '10',
    url: 'strng',
    titulo: 'stringfsdsd22222222',
    description: 'string',
    noticia: 'string',
    imagen_frontal: 'string',
    imagen_mini: 'string',
  },
  {
    id: '11',
    url: 'sing',
    titulo: 'string222555522222',
    description: 'string',
    noticia: 'string',
    imagen_frontal: 'string',
    imagen_mini: 'string',
  },
  {
    id: '12',
    url: 'string',
    titulo: 'string222222ttt22',
    description: 'string',
    noticia: 'string',
    imagen_frontal: 'string',
    imagen_mini: 'string',
  },
  {
    id: '13',
    url: 'string',
    titulo: 'string222rrr22222',
    description: 'string',
    noticia: 'string',
    imagen_frontal: 'string',
    imagen_mini: 'string',
  },
  {
    id: '14',
    url: 'string',
    titulo: 'string222gg22222',
    description: 'string',
    noticia: 'string',
    imagen_frontal: 'string',
    imagen_mini: 'string',
  },
];
